#!/bin/bash
#
#  Tests for bashlock

ERRORS=0
function assert {
	if ! [ $1 $2 $3 ]; then
		echo "ASSERTION FAILED at `caller`: $1 $2 $3"
		let ERRORS=$ERRORS+1
		return 1
	fi
}

. bashlock

bashlock assert "$?" -eq 2 2>/dev/null

bashlock lockfile; assert "$?" -eq 0
bashlock lockfile; assert "$?" -eq 1
bashlock lockfile; assert "$?" -eq 1
rm -f lockfile
bashlock lockfile; assert "$?" -eq 0

echo "$$" >lockfile
bashlock lockfile; assert "$?" -eq 1
bashlock lockfile; assert "$?" -eq 1

bash -c 'echo $$ >lockfile'
bashlock lockfile; assert "$?" -eq 0
bashlock lockfile; assert "$?" -eq 1

BASHLOCKFILE=$(mktemp)
rm "$BASHLOCKFILE"
[ ! -e "$BASHLOCKFILE" ]
assert ! -e "$BASHLOCKFILE"
bashlock; assert "$?" -eq 0
assert -e "$BASHLOCKFILE"
bashlock; assert "$?" -eq 1
rm -f "$BASHLOCKFILE"
bashlock; assert "$?" -eq 0
unset BASHLOCKFILE

bashlock assert "$?" -eq 2 2>/dev/null

if [ "$ERRORS" -ne 0 ]; then
	echo
	echo "ERROR: $ERRORS errors during testing."
	exit 1
fi

echo
echo "Tests complete."
rm -f lockfile
exit 0
